#!/usr/bin/env bash
# Create Entra app registrations for Veeam Presence.
# Simplified from daily_planner — no OBO delegation.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if [[ -f "$PROJECT_ROOT/.env" ]]; then
    set -a; source "$PROJECT_ROOT/.env"; set +a
fi

: "${AZURE_TENANT_ID:?Set AZURE_TENANT_ID}"

echo "=== Veeam Presence App Registrations ==="
echo "Tenant: $AZURE_TENANT_ID"
echo ""

# 1. presence-api app registration
echo "--- Creating presence-api app registration..."
API_APP=$(az ad app create \
    --display-name "Veeam Presence API" \
    --sign-in-audience AzureADMyOrg \
    --output json)

API_APP_ID=$(echo "$API_APP" | jq -r '.appId')
API_OBJECT_ID=$(echo "$API_APP" | jq -r '.id')
echo "  App ID: $API_APP_ID"

# Add access_as_user scope
az ad app update --id "$API_OBJECT_ID" \
    --identifier-uris "api://$API_APP_ID" \
    --output none

SCOPE_ID=$(uuidgen)
az rest --method PATCH \
    --uri "https://graph.microsoft.com/v1.0/applications/$API_OBJECT_ID" \
    --headers "Content-Type=application/json" \
    --body "{\"api\":{\"oauth2PermissionScopes\":[{\"adminConsentDescription\":\"Access Veeam Presence as the signed-in user\",\"adminConsentDisplayName\":\"Access Veeam Presence\",\"id\":\"$SCOPE_ID\",\"isEnabled\":true,\"type\":\"User\",\"userConsentDescription\":\"Access Veeam Presence on your behalf\",\"userConsentDisplayName\":\"Access Veeam Presence\",\"value\":\"access_as_user\"}]}}" \
    --output none

echo "  Scope: access_as_user ($SCOPE_ID)"

# Create service principal
az ad sp create --id "$API_APP_ID" --output none 2>/dev/null || true

# 2. presence-bot app registration
echo "--- Creating presence-bot app registration..."
BOT_APP=$(az ad app create \
    --display-name "Veeam Presence Bot" \
    --sign-in-audience AzureADMyOrg \
    --output json)

BOT_APP_ID=$(echo "$BOT_APP" | jq -r '.appId')
BOT_OBJECT_ID=$(echo "$BOT_APP" | jq -r '.id')
echo "  App ID: $BOT_APP_ID"

# Set identifier URI
az ad app update --id "$BOT_OBJECT_ID" \
    --identifier-uris "api://botid-$BOT_APP_ID" \
    --output none

# Create client secret
BOT_SECRET=$(az ad app credential reset \
    --id "$BOT_OBJECT_ID" \
    --display-name "presence-bot-secret" \
    --years 1 \
    --query password -o tsv)

# Create service principal
az ad sp create --id "$BOT_APP_ID" --output none 2>/dev/null || true

# Pre-authorize Teams clients
TEAMS_WEB="5e3ce6c0-2b1f-4285-8d4b-75ee78787346"
TEAMS_DESKTOP="1fec8e78-bce4-4aaf-ab1b-5451cc387264"
TEAMS_MOBILE="d3590ed6-52b3-4102-aeff-aad2292ab01c"

echo "  Pre-authorizing Teams clients..."
az rest --method PATCH \
    --uri "https://graph.microsoft.com/v1.0/applications/$BOT_OBJECT_ID" \
    --headers "Content-Type=application/json" \
    --body "{\"api\":{\"preAuthorizedApplications\":[{\"appId\":\"$TEAMS_WEB\",\"delegatedPermissionIds\":[\"$SCOPE_ID\"]},{\"appId\":\"$TEAMS_DESKTOP\",\"delegatedPermissionIds\":[\"$SCOPE_ID\"]},{\"appId\":\"$TEAMS_MOBILE\",\"delegatedPermissionIds\":[\"$SCOPE_ID\"]}]}}" \
    --output none 2>/dev/null || echo "  (pre-auth may need manual config)"

# Write outputs
APP_REG_FILE="$PROJECT_ROOT/.env.app-registrations"
cat > "$APP_REG_FILE" << EOF
# Generated by setup-custom-engine-app-registrations.sh — $(date -u +"%Y-%m-%dT%H:%M:%SZ")
API_APP_ID=$API_APP_ID
BOT_APP_ID=$BOT_APP_ID
BOT_APP_PASSWORD=$BOT_SECRET
BOT_SSO_RESOURCE=api://botid-$BOT_APP_ID
AZURE_TENANT_ID=$AZURE_TENANT_ID
EOF

echo ""
echo "=== Done! App registration details in .env.app-registrations ==="
echo "  API App: $API_APP_ID"
echo "  Bot App: $BOT_APP_ID"
echo "  IMPORTANT: Store BOT_APP_PASSWORD securely."
